// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.allStmt, err = db.PrepareContext(ctx, all); err != nil {
		return nil, fmt.Errorf("error preparing query All: %w", err)
	}
	if q.deleteStmt, err = db.PrepareContext(ctx, delete); err != nil {
		return nil, fmt.Errorf("error preparing query Delete: %w", err)
	}
	if q.editStmt, err = db.PrepareContext(ctx, edit); err != nil {
		return nil, fmt.Errorf("error preparing query Edit: %w", err)
	}
	if q.newStmt, err = db.PrepareContext(ctx, new); err != nil {
		return nil, fmt.Errorf("error preparing query New: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.allStmt != nil {
		if cerr := q.allStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allStmt: %w", cerr)
		}
	}
	if q.deleteStmt != nil {
		if cerr := q.deleteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStmt: %w", cerr)
		}
	}
	if q.editStmt != nil {
		if cerr := q.editStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editStmt: %w", cerr)
		}
	}
	if q.newStmt != nil {
		if cerr := q.newStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing newStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db         DBTX
	tx         *sql.Tx
	allStmt    *sql.Stmt
	deleteStmt *sql.Stmt
	editStmt   *sql.Stmt
	newStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:         tx,
		tx:         tx,
		allStmt:    q.allStmt,
		deleteStmt: q.deleteStmt,
		editStmt:   q.editStmt,
		newStmt:    q.newStmt,
	}
}
