// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type User struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Age      int32          `json:"age"`
	Location sql.NullString `json:"location"`
	Email    sql.NullString `json:"email"`
}
