// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const all = `-- name: All :many
SELECT id, name, age, location, email FROM users
`

func (q *Queries) All(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.allStmt, all)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Location,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const delete = `-- name: Delete :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteStmt, delete, id)
	return err
}

const edit = `-- name: Edit :exec
UPDATE users SET name = ?, age = ?, location = ?, email = ? WHERE id = ?
`

type EditParams struct {
	Name     string         `json:"name"`
	Age      int32          `json:"age"`
	Location sql.NullString `json:"location"`
	Email    sql.NullString `json:"email"`
	ID       int32          `json:"id"`
}

func (q *Queries) Edit(ctx context.Context, arg EditParams) error {
	_, err := q.exec(ctx, q.editStmt, edit,
		arg.Name,
		arg.Age,
		arg.Location,
		arg.Email,
		arg.ID,
	)
	return err
}

const new = `-- name: New :exec
INSERT INTO users (name, age, location, email)
VALUES (?, ?, ?, ?)
`

type NewParams struct {
	Name     string         `json:"name"`
	Age      int32          `json:"age"`
	Location sql.NullString `json:"location"`
	Email    sql.NullString `json:"email"`
}

func (q *Queries) New(ctx context.Context, arg NewParams) error {
	_, err := q.exec(ctx, q.newStmt, new,
		arg.Name,
		arg.Age,
		arg.Location,
		arg.Email,
	)
	return err
}
