// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	All(ctx context.Context) ([]User, error)
	Delete(ctx context.Context, id int32) error
	Edit(ctx context.Context, arg EditParams) error
	New(ctx context.Context, arg NewParams) error
}

var _ Querier = (*Queries)(nil)
