// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user.proto

#include "user.pb.h"
#include "user.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace user {

static const char* UserService_method_names[] = {
  "/user.UserService/All",
  "/user.UserService/New",
  "/user.UserService/Edit",
  "/user.UserService/Delete",
};

std::unique_ptr< UserService::Stub> UserService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserService::Stub> stub(new UserService::Stub(channel, options));
  return stub;
}

UserService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_All_(UserService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_New_(UserService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Edit_(UserService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(UserService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserService::Stub::All(::grpc::ClientContext* context, const ::user::GetRequest& request, ::user::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::GetRequest, ::user::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_All_, context, request, response);
}

void UserService::Stub::async::All(::grpc::ClientContext* context, const ::user::GetRequest* request, ::user::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::GetRequest, ::user::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_All_, context, request, response, std::move(f));
}

void UserService::Stub::async::All(::grpc::ClientContext* context, const ::user::GetRequest* request, ::user::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_All_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::GetResponse>* UserService::Stub::PrepareAsyncAllRaw(::grpc::ClientContext* context, const ::user::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::GetResponse, ::user::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_All_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::GetResponse>* UserService::Stub::AsyncAllRaw(::grpc::ClientContext* context, const ::user::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAllRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::New(::grpc::ClientContext* context, const ::user::PostRequest& request, ::user::SuccessResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::PostRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_New_, context, request, response);
}

void UserService::Stub::async::New(::grpc::ClientContext* context, const ::user::PostRequest* request, ::user::SuccessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::PostRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_New_, context, request, response, std::move(f));
}

void UserService::Stub::async::New(::grpc::ClientContext* context, const ::user::PostRequest* request, ::user::SuccessResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_New_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::SuccessResponse>* UserService::Stub::PrepareAsyncNewRaw(::grpc::ClientContext* context, const ::user::PostRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::SuccessResponse, ::user::PostRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_New_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::SuccessResponse>* UserService::Stub::AsyncNewRaw(::grpc::ClientContext* context, const ::user::PostRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNewRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::Edit(::grpc::ClientContext* context, const ::user::PatchRequest& request, ::user::SuccessResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::PatchRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Edit_, context, request, response);
}

void UserService::Stub::async::Edit(::grpc::ClientContext* context, const ::user::PatchRequest* request, ::user::SuccessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::PatchRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Edit_, context, request, response, std::move(f));
}

void UserService::Stub::async::Edit(::grpc::ClientContext* context, const ::user::PatchRequest* request, ::user::SuccessResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Edit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::SuccessResponse>* UserService::Stub::PrepareAsyncEditRaw(::grpc::ClientContext* context, const ::user::PatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::SuccessResponse, ::user::PatchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Edit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::SuccessResponse>* UserService::Stub::AsyncEditRaw(::grpc::ClientContext* context, const ::user::PatchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEditRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::Delete(::grpc::ClientContext* context, const ::user::DeleteRequest& request, ::user::SuccessResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::DeleteRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void UserService::Stub::async::Delete(::grpc::ClientContext* context, const ::user::DeleteRequest* request, ::user::SuccessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::DeleteRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void UserService::Stub::async::Delete(::grpc::ClientContext* context, const ::user::DeleteRequest* request, ::user::SuccessResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::SuccessResponse>* UserService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::user::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::SuccessResponse, ::user::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::SuccessResponse>* UserService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::user::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::GetRequest, ::user::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::GetRequest* req,
             ::user::GetResponse* resp) {
               return service->All(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::PostRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::PostRequest* req,
             ::user::SuccessResponse* resp) {
               return service->New(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::PatchRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::PatchRequest* req,
             ::user::SuccessResponse* resp) {
               return service->Edit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::user::DeleteRequest, ::user::SuccessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::DeleteRequest* req,
             ::user::SuccessResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
}

UserService::Service::~Service() {
}

::grpc::Status UserService::Service::All(::grpc::ServerContext* context, const ::user::GetRequest* request, ::user::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::New(::grpc::ServerContext* context, const ::user::PostRequest* request, ::user::SuccessResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::Edit(::grpc::ServerContext* context, const ::user::PatchRequest* request, ::user::SuccessResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::Delete(::grpc::ServerContext* context, const ::user::DeleteRequest* request, ::user::SuccessResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace user
#include <grpcpp/ports_undef.inc>

