// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user
#ifndef GRPC_user__INCLUDED
#define GRPC_user__INCLUDED

#include "user_generated.h"
#include "flatbuffers/grpc.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace user_fb {

class UserService final {
 public:
  static constexpr char const* service_full_name() {
    return "user_fb.UserService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status All(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, flatbuffers::grpc::Message<GetResponse>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<GetResponse>>> AsyncAll(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<GetResponse>>>(AsyncAllRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<GetResponse>>> PrepareAsyncAll(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<GetResponse>>>(PrepareAsyncAllRaw(context, request, cq));
    }
    virtual ::grpc::Status Add(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>> AsyncAdd(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>> PrepareAsyncAdd(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>>(PrepareAsyncAddRaw(context, request, cq));
    }
    virtual ::grpc::Status Edit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>> AsyncEdit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>>(AsyncEditRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>> PrepareAsyncEdit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>>(PrepareAsyncEditRaw(context, request, cq));
    }
    virtual ::grpc::Status Delete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>> AsyncDelete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>>(AsyncDeleteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>> PrepareAsyncDelete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>>(PrepareAsyncDeleteRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<GetResponse>>* AsyncAllRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<GetResponse>>* PrepareAsyncAllRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>* AsyncAddRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>* AsyncEditRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>* PrepareAsyncEditRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>* AsyncDeleteRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<SuccessResponse>>* PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status All(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, flatbuffers::grpc::Message<GetResponse>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>> AsyncAll(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>>(AsyncAllRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>> PrepareAsyncAll(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>>(PrepareAsyncAllRaw(context, request, cq));
    }
    ::grpc::Status Add(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>> AsyncAdd(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>> PrepareAsyncAdd(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>>(PrepareAsyncAddRaw(context, request, cq));
    }
    ::grpc::Status Edit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>> AsyncEdit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>>(AsyncEditRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>> PrepareAsyncEdit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>>(PrepareAsyncEditRaw(context, request, cq));
    }
    ::grpc::Status Delete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>> AsyncDelete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>>(AsyncDeleteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>> PrepareAsyncDelete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>>(PrepareAsyncDeleteRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>* AsyncAllRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>* PrepareAsyncAllRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* AsyncAddRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* AsyncEditRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* PrepareAsyncEditRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* AsyncDeleteRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_All_;
    const ::grpc::internal::RpcMethod rpcmethod_Add_;
    const ::grpc::internal::RpcMethod rpcmethod_Edit_;
    const ::grpc::internal::RpcMethod rpcmethod_Delete_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status All(::grpc::ServerContext* context, const flatbuffers::grpc::Message<GetRequest>* request, flatbuffers::grpc::Message<GetResponse>* response);
    virtual ::grpc::Status Add(::grpc::ServerContext* context, const flatbuffers::grpc::Message<PostRequest>* request, flatbuffers::grpc::Message<SuccessResponse>* response);
    virtual ::grpc::Status Edit(::grpc::ServerContext* context, const flatbuffers::grpc::Message<PatchRequest>* request, flatbuffers::grpc::Message<SuccessResponse>* response);
    virtual ::grpc::Status Delete(::grpc::ServerContext* context, const flatbuffers::grpc::Message<DeleteRequest>* request, flatbuffers::grpc::Message<SuccessResponse>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_All : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithAsyncMethod_All() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_All() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status All(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<GetRequest>* /*request*/, flatbuffers::grpc::Message<GetResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAll(::grpc::ServerContext* context, flatbuffers::grpc::Message<GetRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<GetResponse>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithAsyncMethod_Add() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PostRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, flatbuffers::grpc::Message<PostRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<SuccessResponse>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Edit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithAsyncMethod_Edit() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Edit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Edit(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PatchRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEdit(::grpc::ServerContext* context, flatbuffers::grpc::Message<PatchRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<SuccessResponse>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithAsyncMethod_Delete() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<DeleteRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelete(::grpc::ServerContext* context, flatbuffers::grpc::Message<DeleteRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<SuccessResponse>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_All<  WithAsyncMethod_Add<  WithAsyncMethod_Edit<  WithAsyncMethod_Delete<  Service   >   >   >   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_All : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithGenericMethod_All() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_All() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status All(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<GetRequest>* /*request*/, flatbuffers::grpc::Message<GetResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithGenericMethod_Add() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PostRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Edit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithGenericMethod_Edit() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Edit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Edit(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PatchRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithGenericMethod_Delete() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<DeleteRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_All : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithStreamedUnaryMethod_All() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<GetRequest>, flatbuffers::grpc::Message<GetResponse>>(std::bind(&WithStreamedUnaryMethod_All<BaseClass>::StreamedAll, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_All() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status All(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<GetRequest>* /*request*/, flatbuffers::grpc::Message<GetResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAll(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<GetRequest>,flatbuffers::grpc::Message<GetResponse>>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithStreamedUnaryMethod_Add() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<PostRequest>, flatbuffers::grpc::Message<SuccessResponse>>(std::bind(&WithStreamedUnaryMethod_Add<BaseClass>::StreamedAdd, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PostRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<PostRequest>,flatbuffers::grpc::Message<SuccessResponse>>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Edit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithStreamedUnaryMethod_Edit() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<PatchRequest>, flatbuffers::grpc::Message<SuccessResponse>>(std::bind(&WithStreamedUnaryMethod_Edit<BaseClass>::StreamedEdit, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Edit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Edit(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PatchRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEdit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<PatchRequest>,flatbuffers::grpc::Message<SuccessResponse>>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Delete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithStreamedUnaryMethod_Delete() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<DeleteRequest>, flatbuffers::grpc::Message<SuccessResponse>>(std::bind(&WithStreamedUnaryMethod_Delete<BaseClass>::StreamedDelete, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Delete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Delete(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<DeleteRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDelete(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<DeleteRequest>,flatbuffers::grpc::Message<SuccessResponse>>* server_unary_streamer) = 0;
  };
  typedef   WithStreamedUnaryMethod_All<  WithStreamedUnaryMethod_Add<  WithStreamedUnaryMethod_Edit<  WithStreamedUnaryMethod_Delete<  Service   >   >   >   >   StreamedUnaryService;
  typedef   Service   SplitStreamedService;
  typedef   WithStreamedUnaryMethod_All<  WithStreamedUnaryMethod_Add<  WithStreamedUnaryMethod_Edit<  WithStreamedUnaryMethod_Delete<  Service   >   >   >   >   StreamedService;
};

}  // namespace user_fb


#endif  // GRPC_user__INCLUDED
