// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USER_USER_H_
#define FLATBUFFERS_GENERATED_USER_USER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace user {

struct GetRequest;
struct GetRequestBuilder;

struct PostRequest;
struct PostRequestBuilder;

struct PatchRequest;
struct PatchRequestBuilder;

struct DeleteRequest;
struct DeleteRequestBuilder;

struct User;
struct UserBuilder;

struct GetResponse;
struct GetResponseBuilder;

struct SuccessResponse;
struct SuccessResponseBuilder;

struct GetRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetRequestBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GetRequestBuilder {
  typedef GetRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit GetRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetRequest> CreateGetRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  GetRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct PostRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PostRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_AGE = 6,
    VT_LOCATION = 8,
    VT_EMAIL = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  const ::flatbuffers::String *location() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOCATION);
  }
  const ::flatbuffers::String *email() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMAIL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_AGE, 4) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_EMAIL) &&
           verifier.VerifyString(email()) &&
           verifier.EndTable();
  }
};

struct PostRequestBuilder {
  typedef PostRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(PostRequest::VT_NAME, name);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(PostRequest::VT_AGE, age, 0);
  }
  void add_location(::flatbuffers::Offset<::flatbuffers::String> location) {
    fbb_.AddOffset(PostRequest::VT_LOCATION, location);
  }
  void add_email(::flatbuffers::Offset<::flatbuffers::String> email) {
    fbb_.AddOffset(PostRequest::VT_EMAIL, email);
  }
  explicit PostRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PostRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PostRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PostRequest> CreatePostRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t age = 0,
    ::flatbuffers::Offset<::flatbuffers::String> location = 0,
    ::flatbuffers::Offset<::flatbuffers::String> email = 0) {
  PostRequestBuilder builder_(_fbb);
  builder_.add_email(email);
  builder_.add_location(location);
  builder_.add_age(age);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PostRequest> CreatePostRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t age = 0,
    const char *location = nullptr,
    const char *email = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto email__ = email ? _fbb.CreateString(email) : 0;
  return user::CreatePostRequest(
      _fbb,
      name__,
      age,
      location__,
      email__);
}

struct PatchRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PatchRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_AGE = 8,
    VT_LOCATION = 10,
    VT_EMAIL = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  const ::flatbuffers::String *location() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOCATION);
  }
  const ::flatbuffers::String *email() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMAIL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_AGE, 4) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_EMAIL) &&
           verifier.VerifyString(email()) &&
           verifier.EndTable();
  }
};

struct PatchRequestBuilder {
  typedef PatchRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(PatchRequest::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(PatchRequest::VT_NAME, name);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(PatchRequest::VT_AGE, age, 0);
  }
  void add_location(::flatbuffers::Offset<::flatbuffers::String> location) {
    fbb_.AddOffset(PatchRequest::VT_LOCATION, location);
  }
  void add_email(::flatbuffers::Offset<::flatbuffers::String> email) {
    fbb_.AddOffset(PatchRequest::VT_EMAIL, email);
  }
  explicit PatchRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PatchRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PatchRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PatchRequest> CreatePatchRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t age = 0,
    ::flatbuffers::Offset<::flatbuffers::String> location = 0,
    ::flatbuffers::Offset<::flatbuffers::String> email = 0) {
  PatchRequestBuilder builder_(_fbb);
  builder_.add_email(email);
  builder_.add_location(location);
  builder_.add_age(age);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PatchRequest> CreatePatchRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *name = nullptr,
    int32_t age = 0,
    const char *location = nullptr,
    const char *email = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto email__ = email ? _fbb.CreateString(email) : 0;
  return user::CreatePatchRequest(
      _fbb,
      id,
      name__,
      age,
      location__,
      email__);
}

struct DeleteRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeleteRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct DeleteRequestBuilder {
  typedef DeleteRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(DeleteRequest::VT_ID, id, 0);
  }
  explicit DeleteRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeleteRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeleteRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeleteRequest> CreateDeleteRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0) {
  DeleteRequestBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct User FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_AGE = 8,
    VT_LOCATION = 10,
    VT_EMAIL = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  const ::flatbuffers::String *location() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOCATION);
  }
  const ::flatbuffers::String *email() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMAIL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_AGE, 4) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_EMAIL) &&
           verifier.VerifyString(email()) &&
           verifier.EndTable();
  }
};

struct UserBuilder {
  typedef User Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(User::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(User::VT_NAME, name);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(User::VT_AGE, age, 0);
  }
  void add_location(::flatbuffers::Offset<::flatbuffers::String> location) {
    fbb_.AddOffset(User::VT_LOCATION, location);
  }
  void add_email(::flatbuffers::Offset<::flatbuffers::String> email) {
    fbb_.AddOffset(User::VT_EMAIL, email);
  }
  explicit UserBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<User> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<User>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<User> CreateUser(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t age = 0,
    ::flatbuffers::Offset<::flatbuffers::String> location = 0,
    ::flatbuffers::Offset<::flatbuffers::String> email = 0) {
  UserBuilder builder_(_fbb);
  builder_.add_email(email);
  builder_.add_location(location);
  builder_.add_age(age);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<User> CreateUserDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *name = nullptr,
    int32_t age = 0,
    const char *location = nullptr,
    const char *email = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto email__ = email ? _fbb.CreateString(email) : 0;
  return user::CreateUser(
      _fbb,
      id,
      name__,
      age,
      location__,
      email__);
}

struct GetResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USERS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<user::User>> *users() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<user::User>> *>(VT_USERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USERS) &&
           verifier.VerifyVector(users()) &&
           verifier.VerifyVectorOfTables(users()) &&
           verifier.EndTable();
  }
};

struct GetResponseBuilder {
  typedef GetResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_users(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<user::User>>> users) {
    fbb_.AddOffset(GetResponse::VT_USERS, users);
  }
  explicit GetResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetResponse> CreateGetResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<user::User>>> users = 0) {
  GetResponseBuilder builder_(_fbb);
  builder_.add_users(users);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetResponse> CreateGetResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<user::User>> *users = nullptr) {
  auto users__ = users ? _fbb.CreateVector<::flatbuffers::Offset<user::User>>(*users) : 0;
  return user::CreateGetResponse(
      _fbb,
      users__);
}

struct SuccessResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SuccessResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           verifier.EndTable();
  }
};

struct SuccessResponseBuilder {
  typedef SuccessResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(SuccessResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  explicit SuccessResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SuccessResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SuccessResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SuccessResponse> CreateSuccessResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false) {
  SuccessResponseBuilder builder_(_fbb);
  builder_.add_success(success);
  return builder_.Finish();
}

inline const user::GetResponse *GetGetResponse(const void *buf) {
  return ::flatbuffers::GetRoot<user::GetResponse>(buf);
}

inline const user::GetResponse *GetSizePrefixedGetResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<user::GetResponse>(buf);
}

template <bool B = false>
inline bool VerifyGetResponseBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<user::GetResponse>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedGetResponseBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<user::GetResponse>(nullptr);
}

inline void FinishGetResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<user::GetResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGetResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<user::GetResponse> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace user

#endif  // FLATBUFFERS_GENERATED_USER_USER_H_
