// Generated by the gRPC C++ plugin.
// FlatBuffers modified generator: native gRPC callback client API enabled when --grpc-callback-api.
// source: user

#include "user_generated.h"
#include "user.grpc.fb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace user_fb {

static const char* UserService_method_names[] = {
  "/user_fb.UserService/All",
  "/user_fb.UserService/Add",
  "/user_fb.UserService/Edit",
  "/user_fb.UserService/Delete",
};

std::unique_ptr< UserService::Stub> UserService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& /*options*/) {
  std::unique_ptr< UserService::Stub> stub(new UserService::Stub(channel));
  return stub;
}

UserService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel)  , rpcmethod_All_(UserService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Add_(UserService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Edit_(UserService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(UserService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}
  
::grpc::Status UserService::Stub::All(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, flatbuffers::grpc::Message<GetResponse>* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_All_, context, request, response);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>* UserService::Stub::AsyncAllRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<GetResponse>>::Create(channel_.get(), cq, rpcmethod_All_, context, request, true);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<GetResponse>>* UserService::Stub::PrepareAsyncAllRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<GetRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<GetResponse>>::Create(channel_.get(), cq, rpcmethod_All_, context, request, false);
}

::grpc::Status UserService::Stub::Add(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Add_, context, request, response);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* UserService::Stub::AsyncAddRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<SuccessResponse>>::Create(channel_.get(), cq, rpcmethod_Add_, context, request, true);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* UserService::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PostRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<SuccessResponse>>::Create(channel_.get(), cq, rpcmethod_Add_, context, request, false);
}

::grpc::Status UserService::Stub::Edit(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Edit_, context, request, response);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* UserService::Stub::AsyncEditRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<SuccessResponse>>::Create(channel_.get(), cq, rpcmethod_Edit_, context, request, true);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* UserService::Stub::PrepareAsyncEditRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<PatchRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<SuccessResponse>>::Create(channel_.get(), cq, rpcmethod_Edit_, context, request, false);
}

::grpc::Status UserService::Stub::Delete(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, flatbuffers::grpc::Message<SuccessResponse>* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Delete_, context, request, response);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* UserService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<SuccessResponse>>::Create(channel_.get(), cq, rpcmethod_Delete_, context, request, true);
}

::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<SuccessResponse>>* UserService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<DeleteRequest>& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< flatbuffers::grpc::Message<SuccessResponse>>::Create(channel_.get(), cq, rpcmethod_Delete_, context, request, false);
}

UserService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, flatbuffers::grpc::Message<GetRequest>, flatbuffers::grpc::Message<GetResponse>>(
          std::mem_fn(&UserService::Service::All), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, flatbuffers::grpc::Message<PostRequest>, flatbuffers::grpc::Message<SuccessResponse>>(
          std::mem_fn(&UserService::Service::Add), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, flatbuffers::grpc::Message<PatchRequest>, flatbuffers::grpc::Message<SuccessResponse>>(
          std::mem_fn(&UserService::Service::Edit), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, flatbuffers::grpc::Message<DeleteRequest>, flatbuffers::grpc::Message<SuccessResponse>>(
          std::mem_fn(&UserService::Service::Delete), this)));
}

UserService::Service::~Service() {
}

::grpc::Status UserService::Service::All(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<GetRequest>* /*request*/, flatbuffers::grpc::Message<GetResponse>* /*response*/) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::Add(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PostRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::Edit(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<PatchRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::Delete(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<DeleteRequest>* /*request*/, flatbuffers::grpc::Message<SuccessResponse>* /*response*/) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace user_fb

