syntax = "proto3";

package user;

option go_package = "pb/user";

service UserService {
  rpc All (GetRequest) returns (GetResponse);
  rpc New (PostRequest) returns (PostResponse);
  rpc Edit (PatchRequest) returns (PatchResponse);
  rpc Delete (DeleteRequest) returns (DeleteResponse);
}

/* -------------------- Requests -------------------- */

message GetRequest {}
message PostRequest {
	string name = 1;
	int32 age = 2;
	string location = 3;
	string email = 4;
}
message PatchRequest {
	int32 id = 1;
	string name = 2;
	int32 age = 3;
	string location = 4;
	string email = 5;
}
message DeleteRequest {
	int32 id = 1;
}