// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod user_fb {

extern crate alloc;

pub enum GetRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GetRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GetRequest<'a> {
  type Inner = GetRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GetRequest<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GetRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args GetRequestArgs
  ) -> ::flatbuffers::WIPOffset<GetRequest<'bldr>> {
    let mut builder = GetRequestBuilder::new(_fbb);
    builder.finish()
  }

}

impl ::flatbuffers::Verifiable for GetRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct GetRequestArgs {
}
impl<'a> Default for GetRequestArgs {
  #[inline]
  fn default() -> Self {
    GetRequestArgs {
    }
  }
}

pub struct GetRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GetRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GetRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GetRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GetRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GetRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GetRequest");
      ds.finish()
  }
}
pub enum PostRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PostRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PostRequest<'a> {
  type Inner = PostRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PostRequest<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_AGE: ::flatbuffers::VOffsetT = 6;
  pub const VT_LOCATION: ::flatbuffers::VOffsetT = 8;
  pub const VT_EMAIL: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PostRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PostRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PostRequest<'bldr>> {
    let mut builder = PostRequestBuilder::new(_fbb);
    if let Some(x) = args.email { builder.add_email(x); }
    if let Some(x) = args.location { builder.add_location(x); }
    builder.add_age(args.age);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PostRequest::VT_NAME, None)}
  }
  #[inline]
  pub fn age(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(PostRequest::VT_AGE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn location(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PostRequest::VT_LOCATION, None)}
  }
  #[inline]
  pub fn email(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PostRequest::VT_EMAIL, None)}
  }
}

impl ::flatbuffers::Verifiable for PostRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<i32>("age", Self::VT_AGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("location", Self::VT_LOCATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("email", Self::VT_EMAIL, false)?
     .finish();
    Ok(())
  }
}
pub struct PostRequestArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub age: i32,
    pub location: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub email: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PostRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    PostRequestArgs {
      name: None,
      age: 0,
      location: None,
      email: None,
    }
  }
}

pub struct PostRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PostRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PostRequest::VT_NAME, name);
  }
  #[inline]
  pub fn add_age(&mut self, age: i32) {
    self.fbb_.push_slot::<i32>(PostRequest::VT_AGE, age, 0);
  }
  #[inline]
  pub fn add_location(&mut self, location: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PostRequest::VT_LOCATION, location);
  }
  #[inline]
  pub fn add_email(&mut self, email: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PostRequest::VT_EMAIL, email);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PostRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PostRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PostRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PostRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PostRequest");
      ds.field("name", &self.name());
      ds.field("age", &self.age());
      ds.field("location", &self.location());
      ds.field("email", &self.email());
      ds.finish()
  }
}
pub enum PatchRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PatchRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PatchRequest<'a> {
  type Inner = PatchRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PatchRequest<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_AGE: ::flatbuffers::VOffsetT = 8;
  pub const VT_LOCATION: ::flatbuffers::VOffsetT = 10;
  pub const VT_EMAIL: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PatchRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PatchRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PatchRequest<'bldr>> {
    let mut builder = PatchRequestBuilder::new(_fbb);
    if let Some(x) = args.email { builder.add_email(x); }
    if let Some(x) = args.location { builder.add_location(x); }
    builder.add_age(args.age);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(PatchRequest::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PatchRequest::VT_NAME, None)}
  }
  #[inline]
  pub fn age(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(PatchRequest::VT_AGE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn location(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PatchRequest::VT_LOCATION, None)}
  }
  #[inline]
  pub fn email(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PatchRequest::VT_EMAIL, None)}
  }
}

impl ::flatbuffers::Verifiable for PatchRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<i32>("age", Self::VT_AGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("location", Self::VT_LOCATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("email", Self::VT_EMAIL, false)?
     .finish();
    Ok(())
  }
}
pub struct PatchRequestArgs<'a> {
    pub id: i32,
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub age: i32,
    pub location: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub email: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PatchRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    PatchRequestArgs {
      id: 0,
      name: None,
      age: 0,
      location: None,
      email: None,
    }
  }
}

pub struct PatchRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PatchRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(PatchRequest::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PatchRequest::VT_NAME, name);
  }
  #[inline]
  pub fn add_age(&mut self, age: i32) {
    self.fbb_.push_slot::<i32>(PatchRequest::VT_AGE, age, 0);
  }
  #[inline]
  pub fn add_location(&mut self, location: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PatchRequest::VT_LOCATION, location);
  }
  #[inline]
  pub fn add_email(&mut self, email: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PatchRequest::VT_EMAIL, email);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PatchRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PatchRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PatchRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PatchRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PatchRequest");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("age", &self.age());
      ds.field("location", &self.location());
      ds.field("email", &self.email());
      ds.finish()
  }
}
pub enum DeleteRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DeleteRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DeleteRequest<'a> {
  type Inner = DeleteRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DeleteRequest<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DeleteRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DeleteRequestArgs
  ) -> ::flatbuffers::WIPOffset<DeleteRequest<'bldr>> {
    let mut builder = DeleteRequestBuilder::new(_fbb);
    builder.add_id(args.id);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DeleteRequest::VT_ID, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DeleteRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct DeleteRequestArgs {
    pub id: i32,
}
impl<'a> Default for DeleteRequestArgs {
  #[inline]
  fn default() -> Self {
    DeleteRequestArgs {
      id: 0,
    }
  }
}

pub struct DeleteRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DeleteRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(DeleteRequest::VT_ID, id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DeleteRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DeleteRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DeleteRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DeleteRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DeleteRequest");
      ds.field("id", &self.id());
      ds.finish()
  }
}
pub enum UserOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct User<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for User<'a> {
  type Inner = User<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> User<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_AGE: ::flatbuffers::VOffsetT = 8;
  pub const VT_LOCATION: ::flatbuffers::VOffsetT = 10;
  pub const VT_EMAIL: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    User { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UserArgs<'args>
  ) -> ::flatbuffers::WIPOffset<User<'bldr>> {
    let mut builder = UserBuilder::new(_fbb);
    if let Some(x) = args.email { builder.add_email(x); }
    if let Some(x) = args.location { builder.add_location(x); }
    builder.add_age(args.age);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(User::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(User::VT_NAME, None)}
  }
  #[inline]
  pub fn age(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(User::VT_AGE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn location(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(User::VT_LOCATION, None)}
  }
  #[inline]
  pub fn email(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(User::VT_EMAIL, None)}
  }
}

impl ::flatbuffers::Verifiable for User<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<i32>("age", Self::VT_AGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("location", Self::VT_LOCATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("email", Self::VT_EMAIL, false)?
     .finish();
    Ok(())
  }
}
pub struct UserArgs<'a> {
    pub id: i32,
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub age: i32,
    pub location: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub email: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for UserArgs<'a> {
  #[inline]
  fn default() -> Self {
    UserArgs {
      id: 0,
      name: None,
      age: 0,
      location: None,
      email: None,
    }
  }
}

pub struct UserBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UserBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(User::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(User::VT_NAME, name);
  }
  #[inline]
  pub fn add_age(&mut self, age: i32) {
    self.fbb_.push_slot::<i32>(User::VT_AGE, age, 0);
  }
  #[inline]
  pub fn add_location(&mut self, location: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(User::VT_LOCATION, location);
  }
  #[inline]
  pub fn add_email(&mut self, email: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(User::VT_EMAIL, email);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UserBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UserBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<User<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for User<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("User");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("age", &self.age());
      ds.field("location", &self.location());
      ds.field("email", &self.email());
      ds.finish()
  }
}
pub enum GetResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GetResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GetResponse<'a> {
  type Inner = GetResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GetResponse<'a> {
  pub const VT_USERS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GetResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GetResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<GetResponse<'bldr>> {
    let mut builder = GetResponseBuilder::new(_fbb);
    if let Some(x) = args.users { builder.add_users(x); }
    builder.finish()
  }


  #[inline]
  pub fn users(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<User<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<User>>>>(GetResponse::VT_USERS, None)}
  }
}

impl ::flatbuffers::Verifiable for GetResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<User>>>>("users", Self::VT_USERS, false)?
     .finish();
    Ok(())
  }
}
pub struct GetResponseArgs<'a> {
    pub users: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<User<'a>>>>>,
}
impl<'a> Default for GetResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    GetResponseArgs {
      users: None,
    }
  }
}

pub struct GetResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GetResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_users(&mut self, users: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<User<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(GetResponse::VT_USERS, users);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GetResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GetResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GetResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GetResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GetResponse");
      ds.field("users", &self.users());
      ds.finish()
  }
}
pub enum SuccessResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SuccessResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SuccessResponse<'a> {
  type Inner = SuccessResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SuccessResponse<'a> {
  pub const VT_SUCCESS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SuccessResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SuccessResponseArgs
  ) -> ::flatbuffers::WIPOffset<SuccessResponse<'bldr>> {
    let mut builder = SuccessResponseBuilder::new(_fbb);
    builder.add_success(args.success);
    builder.finish()
  }


  #[inline]
  pub fn success(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SuccessResponse::VT_SUCCESS, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SuccessResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("success", Self::VT_SUCCESS, false)?
     .finish();
    Ok(())
  }
}
pub struct SuccessResponseArgs {
    pub success: bool,
}
impl<'a> Default for SuccessResponseArgs {
  #[inline]
  fn default() -> Self {
    SuccessResponseArgs {
      success: false,
    }
  }
}

pub struct SuccessResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SuccessResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_success(&mut self, success: bool) {
    self.fbb_.push_slot::<bool>(SuccessResponse::VT_SUCCESS, success, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SuccessResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SuccessResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SuccessResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SuccessResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SuccessResponse");
      ds.field("success", &self.success());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `GetResponse`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_get_response_unchecked`.
pub fn root_as_get_response(buf: &[u8]) -> Result<GetResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<GetResponse>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `GetResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_get_response_unchecked`.
pub fn size_prefixed_root_as_get_response(buf: &[u8]) -> Result<GetResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<GetResponse>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `GetResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_get_response_unchecked`.
pub fn root_as_get_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GetResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<GetResponse<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `GetResponse` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_get_response_unchecked`.
pub fn size_prefixed_root_as_get_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GetResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<GetResponse<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a GetResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `GetResponse`.
pub unsafe fn root_as_get_response_unchecked(buf: &[u8]) -> GetResponse<'_> {
  unsafe { ::flatbuffers::root_unchecked::<GetResponse>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed GetResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `GetResponse`.
pub unsafe fn size_prefixed_root_as_get_response_unchecked(buf: &[u8]) -> GetResponse<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<GetResponse>(buf) }
}
#[inline]
pub fn finish_get_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<GetResponse<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_get_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<GetResponse<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod user_fb

